# Generated by Django 6.0.6 on 2026-06-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='persons_mk/', verbose_name='загрузите фото пресонажа')),
                ('name', models.CharField(max_length=15, verbose_name='укажите имя персонажа')),
                ('age', models.PositiveIntegerField(default=30, verbose_name='укажите возраст')),
                ('kindom', models.CharField(choices=[('земное царство', 'земное царство'), ('внешний мир', 'внешний мир'), ('неизвестно', 'неизвестно')], default='земное царство', max_length=100, verbose_name='укажите царство обитания персонажа')),
                ('description', models.TextField(blank=True, verbose_name='укажите описание персонажа')),
                ('video_fight', models.URLField(verbose_name='укажите ссылку на бой')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
