# Generated by Django 6.0.6 on 2026-06-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortal_kombat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название новости')),
                ('description', models.TextField(verbose_name='укажите новость')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.AlterModelOptions(
            name='personmk',
            options={'verbose_name': 'персонажа', 'verbose_name_plural': 'персонажи'},
        ),
    ]
