# Generated by Django 6.0.6 on 2026-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortal_kombat', '0002_newsmk_alter_personmk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmk',
            name='emodji',
            field=models.CharField(max_length=1, null=True, verbose_name='укажите эмодзи'),
        ),
    ]
