# Generated by Django 6.0.6 on 2026-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortal_kombat', '0003_newsmk_emodji'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmk',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
