# Generated by Django 6.0.6 on 2026-07-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mortal_kombat', '0003_newsmk_emodji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('personal_data', models.FileField(upload_to='competitions/')),
                ('cash', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('choice_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortal_kombat.personmk', verbose_name='fighter')),
            ],
        ),
    ]
