# Generated by Django 6.0.6 on 2026-06-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='какого персонажа выбираете?')),
                ('weapon', models.CharField(max_length=100, verbose_name='каким оружием атакуете?')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pers', models.CharField(default='Иван', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('select_hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.hero')),
            ],
        ),
    ]
