# Generated by Django 6.0.6 on 2026-06-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='4', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('select_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.hero')),
            ],
        ),
    ]
