# Generated by Django 6.0.6 on 2026-06-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reviewhero'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='fight_location',
            field=models.ManyToManyField(null=True, to='products.fightlocation'),
        ),
    ]
