# Generated by Django 6.0.6 on 2026-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_fightlocation_hero_fight_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='fight_location',
            field=models.ManyToManyField(blank=True, null=True, to='products.fightlocation'),
        ),
    ]
