# Generated by Django 6.0.6 on 2026-06-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_hero_fight_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='select_hero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.hero'),
        ),
    ]
